title: Haoran Zheng
logo: /assets/IMG/IMG_2948.jpeg
description: |
  AI Researcher - the University of Chicago
  ğŸ“:(513)909-5366 <br>
  âœ‰ï¸:Haoran.Zheng@chicagobooth.edu <br>
  [LinkedIn](https://www.linkedin.com/in/haoran-zheng-04a9551ba/)
show_downloads: false
theme: jekyll-theme-minimal
