title: Haoran Zheng
logo: /assets/IMG/IMG_2948.jpeg
description: |
  AI Researcher - the University of Chicago <br>
  ğŸ“:(513)909-5366 | <a href="https://www.linkedin.com/in/haoran-zheng-04a9551ba/">LinkedIn Profile</a> <br>
  âœ‰ï¸:Haoran.Zheng@chicagobooth.edu 
show_downloads: false
theme: jekyll-theme-minimal
